### ISSUE TITLE
Encoding of source file for R 4.2.x

### ISSUE THREAD

**Issue by raniets** [helseprofil/khfunctions#50]
R 4.2.x has a change in the default way of handling encoding. We see during a run that Norwegian characters ÆØÅ in khfunctions console messages are scrambled, they show as "tilted squares with a question mark". My guess is that the immediate cause is that the .R file itself is saved in the default Windows encoding and not in UTF-8.
There are a few places in KHfunctions.R where ÆØÅ are used in code lines, e.g. in regular expressions (not just in comments or messages). We should ensure that these code lines are correctly read also in R 4.2.x. 
If we need to be able to run the script regardless of R version, would it be suitable to replace these characters in the expressions with explicit character codes (not "Æ" but "/u00C6")? I'm not sure whether this would be sufficient ...

**Comment by ybkamaleri** [comment]
That is the safest way to replace all the norwegian character to unicode. You can test with one of the filegroup you know using at least one of these characters. By the way, the slash should be backward ie. `\U00C6`. 

You can test in R concole with `cat("\U00C6")`

**Comment by vegardlysne** [comment]
Closed, encoding challenges are fixed.
