### ISSUE TITLE
Play a sound when a command is finished

### ISSUE THREAD

**Issue by raniets** [helseprofil/khfunctions#56]
I often run khfunctions commands on a separate desktop, or I can have other windows covering the RStudio window. It would be nice if there was a sound to tell that the command has finished.
A possible problem is how to make that sound on the local PC when running khfunctions remotely (via RDP).
A suggestion for a sound package is 'beepr'. This is used in the Auto_backup script I use for KHELSA.mdb.

**Comment by vegardlysne** [comment]
Suggestion: 

add argument sound = FALSE, and at the end of the functions add: 

if(isTRUE(sound) beepr::beep()
